### ISSUE TITLE
渔业时间

### ISSUE THREAD

**Issue by FlandreTL** [1CPOWER/ColderCaesar#1]
左下角有文字，职业也增加了经验，但是非常高的几率不给鱼。
新增莫名乱码
![~I658Q T2YB42YCZ6 L%7E2](https://user-images.githubusercontent.com/49860893/73332644-536cdd00-42a2-11ea-87ba-005ec6c3351a.png)

**Comment by 1CPOWER** [comment]
已解决此BUG 日期混乱*
